config:
  validation: true
  warningsAsErrors: false

complexity:
  ComplexCondition:
    active: true
    allowedConditions: 3
  CyclomaticComplexMethod:
    active: true
    allowedComplexity: 14
  LongMethod:
    active: false
  LongParameterList:
    active: true
    ignoreDefaultParameters: true
  TooManyFunctions:
    active: true
    allowedFunctionsPerFile: 11
    allowedFunctionsPerClass: 11

exceptions:
  TooGenericExceptionCaught:
    active: true

naming:
  ConstructorParameterNaming:
    active: false
  FunctionNaming:
    active: false
  MatchingDeclarationName:
    active: false
  TopLevelPropertyNaming:
    active: true

style:
  ForbiddenImport:
    active: true
    forbiddenImports:
      - "androidx.compose.material.icons.**"
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 140
  NewLineAtEndOfFile:
    active: true
  ReturnCount:
    active: true
    max: 2
    excludeGuardClauses: false
  WildcardImport:
    active: true
