config:
  validation: true
  warningsAsErrors: false

complexity:
  ComplexCondition:
    active: false
  CyclomaticComplexMethod:
    active: false
  LongMethod:
    active: false
  LongParameterList:
    active: true
    ignoreDefaultParameters: true
  TooManyFunctions:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: true

naming:
  ConstructorParameterNaming:
    active: false
  FunctionNaming:
    active: false
  MatchingDeclarationName:
    active: false
  TopLevelPropertyNaming:
    active: false

style:
  ForbiddenImport:
    active: true
    forbiddenImports:
      - "androidx.compose.material.icons.**"
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 160
  NewLineAtEndOfFile:
    active: true
  ReturnCount:
    active: false
  WildcardImport:
    active: true
